name: Live
run-name: Run regulary to awoid AWS account deletion
on:
  schedule:
  - cron: "21 4 2 * *"
  workflow_dispatch:
  workflow_run:
    workflows: [ Test ]
    types: [ completed ]
jobs:
  Live:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/live.yml/enable"
      env:
        GH_TOKEN: ${{ github.token }}
    - run: npm install
    - name: Export variables and secrets
      run: jq -r 'to_entries[]|"\(.key)=\(.value)"' <<< '${{toJSON(secrets)}}${{toJSON(vars)}}' >> $GITHUB_ENV
    - run: npx lj t test/live.js

